/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        mq: {
          navy:    '#0F172A',
          '800':   '#1E293B',
          '700':   '#334155',
          '600':   '#475569',
          teal:    '#0D9488',
          't400':  '#2DD4BF',
          't600':  '#0F766E',
          't900':  '#042F2E',
          slate:   '#F8FAFC',
          's200':  '#E2E8F0',
          's400':  '#94A3B8',
          's600':  '#475569',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', '14px'],
        'hero': ['72px', { lineHeight: '1.02', letterSpacing: '-3px' }],
        'display': ['48px', { lineHeight: '1.1', letterSpacing: '-1.5px' }],
        'title': ['32px', { lineHeight: '1.2', letterSpacing: '-0.8px' }],
      },
      animation: {
        'float':        'float 7s ease-in-out infinite',
        'float-slow':   'float 9s ease-in-out infinite 1s',
        'float-fast':   'float 5s ease-in-out infinite 2s',
        'ticker':       'ticker 25s linear infinite',
        'pulse-dot':    'pulseDot 2s ease-in-out infinite',
        'fade-up':      'fadeUp .7s cubic-bezier(.34,1.56,.64,1) both',
        'fade-up-d1':   'fadeUp .7s cubic-bezier(.34,1.56,.64,1) .1s both',
        'fade-up-d2':   'fadeUp .7s cubic-bezier(.34,1.56,.64,1) .2s both',
        'fade-up-d3':   'fadeUp .7s cubic-bezier(.34,1.56,.64,1) .3s both',
        'scale-in':     'scaleIn .5s cubic-bezier(.34,1.56,.64,1) both',
        'slide-right':  'slideRight .4s cubic-bezier(.34,1.56,.64,1) both',
        'glow-pulse':   'glowPulse 3s ease-in-out infinite',
        'skeleton':     'skeleton 1.8s ease-in-out infinite',
        'spin-slow':    'spin 8s linear infinite',
        'count-up':     'countUp .8s ease-out both',
        'draw-line':    'drawLine 1.5s ease forwards',
        'confetti':     'confetti 1s ease-out forwards',
      },
      keyframes: {
        float:      { '0%,100%': { transform: 'translateY(0)' },
                      '50%':     { transform: 'translateY(-14px)' } },
        ticker:     { '0%':   { transform: 'translateX(0)' },
                      '100%': { transform: 'translateX(-50%)' } },
        pulseDot:   { '0%,100%': { opacity: '1', transform: 'scale(1)' },
                      '50%':     { opacity: '.3', transform: 'scale(.6)' } },
        fadeUp:     { from: { opacity: '0', transform: 'translateY(28px)' },
                      to:   { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:    { from: { opacity: '0', transform: 'scale(.88)' },
                      to:   { opacity: '1', transform: 'scale(1)' } },
        slideRight: { from: { opacity: '0', transform: 'translateX(40px)' },
                      to:   { opacity: '1', transform: 'translateX(0)' } },
        glowPulse:  { '0%,100%': { boxShadow: '0 0 20px rgba(13,148,136,.2)' },
                      '50%':     { boxShadow: '0 0 60px rgba(13,148,136,.6)' } },
        skeleton:   { '0%,100%': { opacity: '.4' },
                      '50%':     { opacity: '.9' } },
        countUp:    { from: { opacity: '0', transform: 'translateY(10px)' },
                      to:   { opacity: '1', transform: 'translateY(0)' } },
        drawLine:   { from: { strokeDashoffset: '400' },
                      to:   { strokeDashoffset: '0' } },
        confetti:   { '0%':   { transform: 'translateY(0) rotate(0)',   opacity: '1' },
                      '100%': { transform: 'translateY(80px) rotate(360deg)', opacity: '0' } },
      },
      boxShadow: {
        'teal-glow':    '0 0 50px rgba(13,148,136,.4)',
        'teal-glow-sm': '0 0 20px rgba(13,148,136,.2)',
        'teal-glow-lg': '0 0 90px rgba(13,148,136,.55)',
        'glass':        '0 8px 40px rgba(0,0,0,.35)',
        'glass-lg':     '0 20px 80px rgba(0,0,0,.5)',
        'card':         '0 2px 16px rgba(0,0,0,.08)',
        'card-hover':   '0 8px 32px rgba(0,0,0,.14)',
        'navy':         '0 8px 32px rgba(15,23,42,.6)',
        'purple-glow':  '0 0 30px rgba(124,58,237,.3)',
        'inner-teal':   'inset 0 1px 0 rgba(45,212,191,.15)',
      },
      backgroundImage: {
        'grid-teal': `
          linear-gradient(rgba(13,148,136,.05) 1px, transparent 1px),
          linear-gradient(90deg, rgba(13,148,136,.05) 1px, transparent 1px)
        `,
        'gradient-teal': 'linear-gradient(135deg, #0D9488, #2DD4BF)',
        'gradient-navy': 'linear-gradient(135deg, #0F172A, #1E293B)',
        'gradient-hero': 'linear-gradient(135deg, #0F172A 0%, #0D2B2B 50%, #0F172A 100%)',
        'card-shine':    'linear-gradient(135deg, rgba(255,255,255,.03) 0%, transparent 50%)',
      },
      backgroundSize: {
        'grid': '60px 60px',
      },
      borderRadius: {
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
      },
      transitionDuration: {
        '400': '400ms',
        '600': '600ms',
      },
      spacing: {
        '18': '72px',
        '22': '88px',
      },
    },
  },
  plugins: [],
};
